apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    description: "Kimi Coding Documentation"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/coding/docs/(.*)$ {
        return 302 /code/docs/$1;
      }
  labels:
    env: test
    app: kimi-coding-docs
  name: kimi-coding-docs
  namespace: agent
spec:
  ingressClassName: nginx-in
  rules:
  - host: kimi-coding-docs.deva.msh.team
    http:
      paths:
      - backend:
          service:
            name: kimi-coding-docs
            port:
              name: http
        path: /code/docs/
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - kimi-coding-docs.deva.msh.team
    secretName: tls-deva-msh-team
