// Paste into Playwright browser_evaluate — iterates all pages via navigate.
// Since evaluate is single-page, this file just documents the URL list
// used for the walk driven from the MCP tool.
export const URLS = [
  '/code/docs/',
  '/code/docs/kimi-code/faq',
  '/code/docs/kimi-code-cli/getting-started',
  '/code/docs/kimi-code-cli/core-operations',
  '/code/docs/kimi-code-cli/configuration/configuration-files',
  '/code/docs/kimi-code-cli/configuration/environment-variables',
  '/code/docs/kimi-code-cli/configuration/providers-and-models',
  '/code/docs/kimi-code-cli/configuration/data-locations',
  '/code/docs/kimi-code-cli/configuration/overrides-and-precedence',
  '/code/docs/kimi-code-cli/customization/mcp',
  '/code/docs/kimi-code-cli/customization/hooks',
  '/code/docs/kimi-code-cli/customization/plugins',
  '/code/docs/kimi-code-cli/customization/skills',
  '/code/docs/kimi-code-cli/customization/sub-agents',
  '/code/docs/kimi-code-cli/customization/wire-protocol',
  '/code/docs/kimi-code-cli/reference/kimi-command',
  '/code/docs/kimi-code-cli/reference/kimi-acp',
  '/code/docs/kimi-code-cli/reference/kimi-info',
  '/code/docs/kimi-code-cli/reference/kimi-mcp',
  '/code/docs/kimi-code-cli/reference/kimi-term',
  '/code/docs/kimi-code-cli/reference/kimi-vis',
  '/code/docs/kimi-code-cli/reference/kimi-web',
  '/code/docs/kimi-code-cli/reference/slash-commands',
  '/code/docs/kimi-code-cli/reference/keyboard-shortcuts',
  '/code/docs/kimi-code-for-vscode/getting-started',
  '/code/docs/kimi-code-for-vscode/core-operations',
  '/code/docs/kimi-code-for-vscode/configuration',
  '/code/docs/kimi-code-for-vscode/customization',
  '/code/docs/third-party-tools/jetbrains',
  '/code/docs/third-party-tools/zed',
  '/code/docs/third-party-tools/zsh',
  '/code/docs/third-party-tools/other-coding-agents',
];
